# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nflxprofile.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nflxprofile.proto\x12\x0bnflxprofile\"7\n\x04\x46ile\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x0c\n\x04line\x18\x02 \x01(\r\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\r\"U\n\nStackFrame\x12\x15\n\rfunction_name\x18\x01 \x02(\t\x12\x0f\n\x07libtype\x18\x02 \x01(\t\x12\x1f\n\x04\x66ile\x18\x03 \x01(\x0b\x32\x11.nflxprofile.File\"\xc1\x05\n\x07Profile\x12\x12\n\nstart_time\x18\x01 \x02(\x01\x12\x10\n\x08\x65nd_time\x18\x02 \x02(\x01\x12\x13\n\x07samples\x18\x03 \x03(\rB\x02\x10\x01\x12\x17\n\x0btime_deltas\x18\x04 \x03(\x01\x42\x02\x10\x01\x12.\n\x05nodes\x18\x05 \x03(\x0b\x32\x1f.nflxprofile.Profile.NodesEntry\x12\r\n\x05title\x18\x06 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x07 \x01(\t\x12\x30\n\x06params\x18\x08 \x03(\x0b\x32 .nflxprofile.Profile.ParamsEntry\x12\x17\n\x0bsamples_cpu\x18\t \x03(\rB\x02\x10\x01\x12\x17\n\x0bsamples_pid\x18\n \x03(\rB\x02\x10\x01\x12\x17\n\x0bsamples_tid\x18\x0b \x03(\rB\x02\x10\x01\x12\x19\n\rsamples_value\x18\x0c \x03(\x04\x42\x02\x10\x01\x12\x19\n\x11idle_sample_count\x18\r \x01(\r\x1a\xe2\x01\n\x04Node\x12\x15\n\rfunction_name\x18\x01 \x02(\t\x12\x11\n\thit_count\x18\x02 \x02(\r\x12\x10\n\x08\x63hildren\x18\x03 \x03(\r\x12\x0f\n\x07libtype\x18\x04 \x01(\t\x12\x0e\n\x06parent\x18\x05 \x01(\r\x12\x0b\n\x03pid\x18\x06 \x01(\r\x12\x0b\n\x03tid\x18\x07 \x01(\r\x12\x0b\n\x03\x63pu\x18\x08 \x01(\r\x12\r\n\x05value\x18\t \x01(\x04\x12&\n\x05stack\x18\n \x03(\x0b\x32\x17.nflxprofile.StackFrame\x12\x1f\n\x04\x66ile\x18\x0b \x01(\x0b\x32\x11.nflxprofile.File\x1aG\n\nNodesEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.nflxprofile.Profile.Node:\x02\x38\x01\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nflxprofile_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROFILE_NODESENTRY._options = None
  _PROFILE_NODESENTRY._serialized_options = b'8\001'
  _PROFILE_PARAMSENTRY._options = None
  _PROFILE_PARAMSENTRY._serialized_options = b'8\001'
  _PROFILE.fields_by_name['samples']._options = None
  _PROFILE.fields_by_name['samples']._serialized_options = b'\020\001'
  _PROFILE.fields_by_name['time_deltas']._options = None
  _PROFILE.fields_by_name['time_deltas']._serialized_options = b'\020\001'
  _PROFILE.fields_by_name['samples_cpu']._options = None
  _PROFILE.fields_by_name['samples_cpu']._serialized_options = b'\020\001'
  _PROFILE.fields_by_name['samples_pid']._options = None
  _PROFILE.fields_by_name['samples_pid']._serialized_options = b'\020\001'
  _PROFILE.fields_by_name['samples_tid']._options = None
  _PROFILE.fields_by_name['samples_tid']._serialized_options = b'\020\001'
  _PROFILE.fields_by_name['samples_value']._options = None
  _PROFILE.fields_by_name['samples_value']._serialized_options = b'\020\001'
  _FILE._serialized_start=34
  _FILE._serialized_end=89
  _STACKFRAME._serialized_start=91
  _STACKFRAME._serialized_end=176
  _PROFILE._serialized_start=179
  _PROFILE._serialized_end=884
  _PROFILE_NODE._serialized_start=538
  _PROFILE_NODE._serialized_end=764
  _PROFILE_NODESENTRY._serialized_start=766
  _PROFILE_NODESENTRY._serialized_end=837
  _PROFILE_PARAMSENTRY._serialized_start=839
  _PROFILE_PARAMSENTRY._serialized_end=884
# @@protoc_insertion_point(module_scope)
